# Generated by Django 5.2.5 on 2025-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationsFamiliales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_registre', models.CharField(max_length=64, unique=True, verbose_name='N° registre')),
                ('date_sortie', models.DateField(verbose_name='Date sortie')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('emetteur', models.CharField(choices=[('DG', 'DG'), ('DGA', 'DGA')], max_length=3, verbose_name='Émetteur')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], max_length=6, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Allocations familiales',
                'verbose_name_plural': 'Allocations familiales',
            },
        ),
        migrations.CreateModel(
            name='AllocationsPrenatales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_registre', models.CharField(max_length=64, unique=True, verbose_name='N° registre')),
                ('date_sortie', models.DateField(verbose_name='Date sortie')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('emetteur', models.CharField(choices=[('DG', 'DG'), ('DGA', 'DGA')], max_length=3, verbose_name='Émetteur')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], max_length=6, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Allocations prénatales',
                'verbose_name_plural': 'Allocations prénatales',
            },
        ),
        migrations.CreateModel(
            name='Chrono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_registre', models.CharField(max_length=64, unique=True, verbose_name='N° registre')),
                ('date_sortie', models.DateField(verbose_name='Date sortie')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('emetteur', models.CharField(choices=[('DG', 'DG'), ('DGA', 'DGA')], max_length=3, verbose_name='Émetteur')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], max_length=6, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Chrono',
                'verbose_name_plural': 'Chronos',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_registre', models.CharField(max_length=64, unique=True, verbose_name='N° registre')),
                ('date_sortie', models.DateField(verbose_name='Date sortie')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('emetteur', models.CharField(choices=[('DG', 'DG'), ('DGA', 'DGA')], max_length=3, verbose_name='Émetteur')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], max_length=6, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Décision',
                'verbose_name_plural': 'Décisions',
            },
        ),
        migrations.CreateModel(
            name='DocumentEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_entree', models.CharField(max_length=64, unique=True, verbose_name='N° entrée')),
                ('date_reception', models.DateField(verbose_name='Date réception')),
                ('expediteur', models.CharField(max_length=255, verbose_name='Expéditeur')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(choices=[('SDG', 'SDG'), ('DRH', 'DRH'), ('SOS', 'SOS'), ('DDF', 'DDF'), ('DF', 'DF'), ('DEO', 'DEO'), ('DJ', 'DJ'), ('DT', 'DT'), ('DAI', 'DAI'), ('DGI-O', 'DGI-O'), ('DASS', 'DASS'), ('DIREC', 'DIREC'), ('DSG', 'DSG'), ('DIPREV', 'DIPREV'), ('POFUPOP', 'POFUPOP'), ('CM MATONGE', 'CM MATONGE'), ('DUK-N', 'DUK-N'), ('DUK-S', 'DUK-S'), ('DUK-E', 'DUK-E'), ('DUK-O', 'DUK-O'), ('DUK-C', 'DUK-C'), ('DIUK-NE', 'DIUK-NE'), ('DUK-DE', 'DUK-DE'), ('DUK-CO', 'DUK-CO'), ('CTI', 'CTI'), ('PRESSE', 'PRESSE'), ('CALL CENTER', 'CALL CENTER')], max_length=32, verbose_name='Destinataire')),
                ('annotations_autorite', models.TextField(blank=True, verbose_name='Annotations de l’autorité')),
            ],
            options={
                'verbose_name': 'Document entrant',
                'verbose_name_plural': 'Documents entrants',
                'ordering': ['-date_reception', '-numero_ordre'],
            },
        ),
        migrations.CreateModel(
            name='Gouvernement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_registre', models.CharField(max_length=64, unique=True, verbose_name='N° registre')),
                ('date_sortie', models.DateField(verbose_name='Date sortie')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('emetteur', models.CharField(choices=[('DG', 'DG'), ('DGA', 'DGA')], max_length=3, verbose_name='Émetteur')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], max_length=6, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Gouvernement',
                'verbose_name_plural': 'Gouvernements',
            },
        ),
        migrations.CreateModel(
            name='OrdreMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_registre', models.CharField(max_length=64, unique=True, verbose_name='N° registre')),
                ('date_sortie', models.DateField(verbose_name='Date sortie')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('emetteur', models.CharField(choices=[('DG', 'DG'), ('DGA', 'DGA')], max_length=3, verbose_name='Émetteur')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], max_length=6, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Ordre de mission',
                'verbose_name_plural': 'Ordres de mission',
            },
        ),
        migrations.CreateModel(
            name='PrestationsFamilles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('numero_registre', models.CharField(max_length=64, unique=True, verbose_name='N° registre')),
                ('date_sortie', models.DateField(verbose_name='Date sortie')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('emetteur', models.CharField(choices=[('DG', 'DG'), ('DGA', 'DGA')], max_length=3, verbose_name='Émetteur')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], max_length=6, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Prestations aux familles',
                'verbose_name_plural': 'Prestations aux familles',
            },
        ),
    ]
