# Generated by Django 5.2.5 on 2025-08-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententrant',
            name='nature_document',
            field=models.CharField(choices=[('KIN', 'Kinshasa'), ('PROV', 'Province')], default='KIN', max_length=5, verbose_name='Nature document'),
        ),
    ]
