# Generated by Django 5.2.5 on 2025-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documententrant_nature_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententrant',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='entrants/%Y/%m/%d/', verbose_name='Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='documententrant',
            name='nature_document',
            field=models.CharField(choices=[('KIN', 'Kinshasa'), ('PROV', 'Province')], default='KIN', max_length=5, verbose_name='Provenance'),
        ),
    ]
