# Generated by Django 5.2.5 on 2025-09-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documententrant_piece_jointe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententrant',
            name='date_document_retourne',
            field=models.DateField(blank=True, null=True, verbose_name='Date document retourné'),
        ),
    ]
