# Generated by Django 5.2.5 on 2025-11-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documententrant_destinataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='documententrant',
            name='objet_document_retourne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objet document retourné'),
        ),
    ]
