# Generated by Django 5.2.5 on 2026-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documententrant_objet_document_retourne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordremission',
            name='emetteur',
        ),
        migrations.RemoveField(
            model_name='ordremission',
            name='statut',
        ),
        migrations.AddField(
            model_name='ordremission',
            name='destination_mission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination de la mission'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='nombre_jours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de jours'),
        ),
        migrations.AlterField(
            model_name='ordremission',
            name='destinataire',
            field=models.CharField(max_length=255, verbose_name='Personne(s) désigné(es)'),
        ),
    ]
