# Generated by Django 5.2.5 on 2026-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_ordremission_emetteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordremission',
            name='statut',
            field=models.CharField(choices=[('SIGNE', 'Signé'), ('REFUS', 'Refus')], default='SIGNE', max_length=6, verbose_name='Statut'),
        ),
    ]
