# Generated by Django 5.2.5 on 2026-01-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_ordremission_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documententrant',
            name='numero_entree',
            field=models.CharField(max_length=64, verbose_name='N° entrée'),
        ),
        migrations.AddConstraint(
            model_name='documententrant',
            constraint=models.UniqueConstraint(fields=('nature_document', 'numero_entree'), name='uniq_numero_entree_par_nature'),
        ),
    ]
