# Generated by Django 5.2.5 on 2026-01-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_documententrant_numero_entree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documententrant',
            name='destinataire',
            field=models.CharField(blank=True, choices=[('SDG', 'SDG'), ('DRH', 'DRH'), ('SOS', 'SOS'), ('DDF', 'DDF'), ('DF', 'DF'), ('DEO', 'DEO'), ('DJ', 'DJ'), ('DT', 'DT'), ('DAI', 'DAI'), ('DGI-O', 'DGI-O'), ('DASS', 'DASS'), ('DIREC', 'DIREC'), ('DSG', 'DSG'), ('DIPREV', 'DIPREV'), ('POFUPOP', 'POFUPOP'), ('CM MATONGE', 'CM MATONGE'), ('DUK-N', 'DUK-N'), ('DUK-S', 'DUK-S'), ('DUK-E', 'DUK-E'), ('DUK-O', 'DUK-O'), ('DUK-C', 'DUK-C'), ('DIUK-NE', 'DIUK-NE'), ('DUK-DE', 'DUK-DE'), ('DUK-CO', 'DUK-CO'), ('CTI', 'CTI'), ('PRESSE', 'PRESSE'), ('CALL CENTER', 'CALL CENTER'), ('COURRIER', 'COURRIER'), ('CGPMP', 'CGPMP')], max_length=32, verbose_name='Destinataire'),
        ),
    ]
