# Generated by Django 5.2.5 on 2026-01-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_documententrant_destinataire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrestationsFamilles',
            new_name='PaiementPrestationsSociales',
        ),
        migrations.AlterModelOptions(
            name='paiementprestationssociales',
            options={'verbose_name': 'Paiement prestations sociales', 'verbose_name_plural': 'Paiements prestations sociales'},
        ),
    ]
