# Generated by Django 5.2.5 on 2026-01-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_rename_prestationsfamilles_paiementprestationssociales_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documententrant',
            name='uniq_numero_entree_par_nature',
        ),
    ]
