# Generated by Django 5.2.5 on 2026-01-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_documententrant_uniq_numero_entree_par_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documententrant',
            name='destinataire',
            field=models.CharField(blank=True, choices=[('SDG', 'SDG'), ('DRH', 'DRH'), ('SOS', 'SOS'), ('DDF', 'DDF'), ('DF', 'DF'), ('DEO', 'DEO'), ('DJ', 'DJ'), ('DT', 'DT'), ('DAI', 'DAI'), ('DGI-O', 'DGI-O'), ('DASS', 'DASS'), ('DIREC', 'DIREC'), ('DSG', 'DSG'), ('DIPREV', 'DIPREV'), ('POFUPOP', 'POFUPOP'), ('CM MATONGE', 'CM MATONGE'), ('DUK-N', 'DUK-N'), ('DUK-S', 'DUK-S'), ('DUK-E', 'DUK-E'), ('DUK-O', 'DUK-O'), ('DUK-C', 'DUK-C'), ('DUK-NE', 'DUK-NE'), ('DUK-E', 'DUK-E'), ('DUK-SE', 'DUK-SE'), ('AP', 'AP'), ('AA', 'AA'), ('AJ', 'AJ'), ('AM', 'AM'), ('AREC', 'AREC'), ('AF', 'AF'), ('AT', 'AT'), ('DGI-E', 'DGI-E'), ('DP KATANGA I', 'DP KATANGA I'), ('CTI', 'CTI'), ('SCE PRESSE', 'SCE PRESSE'), ('CALL CENTER', 'CALL CENTER'), ('COURRIER', 'COURRIER'), ('CGPMP', 'CGPMP'), ('AFCNSS', 'AFCNSS')], max_length=32, verbose_name='Destinataire'),
        ),
    ]
