# Generated by Django 5.2.10 on 2026-02-04 10:03

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_documententrant_destinataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documententrant',
            name='destinataire',
            field=models.CharField(blank=True, choices=[('SDG', 'SDG'), ('DRH', 'DRH'), ('SOS', 'SOS'), ('DDF', 'DDF'), ('DF', 'DF'), ('DEO', 'DEO'), ('DJ', 'DJ'), ('DT', 'DT'), ('DAI', 'DAI'), ('DGI-O', 'DGI-O'), ('DASS', 'DASS'), ('DIREC', 'DIREC'), ('DSG', 'DSG'), ('DIPREV', 'DIPREV'), ('POFUPOP', 'POFUPOP'), ('CM MATONGE', 'CM MATONGE'), ('DUK-N', 'DUK-N'), ('DUK-S', 'DUK-S'), ('DUK-E', 'DUK-E'), ('DUK-O', 'DUK-O'), ('DUK-C', 'DUK-C'), ('DUK-NE', 'DUK-NE'), ('DUK-SE', 'DUK-SE'), ('AP', 'AP'), ('AA', 'AA'), ('AJ', 'AJ'), ('AM', 'AM'), ('AREC', 'AREC'), ('AF', 'AF'), ('AT', 'AT'), ('DGI-E', 'DGI-E'), ('DP KATANGA I', 'DP KATANGA I'), ('CTI', 'CTI'), ('SCE PRESSE', 'SCE PRESSE'), ('CALL CENTER', 'CALL CENTER'), ('COURRIER', 'COURRIER'), ('CGPMP', 'CGPMP'), ('AFCNSS', 'AFCNSS')], max_length=32, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='documententrant',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.private_piece_jointe_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']), documents.models.validate_file_size], verbose_name='Pièce jointe'),
        ),
    ]
